#!/usr/bin/env python
"""Execute the tests for post_pro.

The golden test outputs are generated by the script generate_outputs.sh.

You have to give the root paths to the source and the binaries as arguments to
the program.  These are the paths to the directory that contains the 'projects'
directory.

Usage:  run_tests.py SOURCE_ROOT_PATH BINARY_ROOT_PATH
"""
import logging
import os.path
import sys

# Automagically add util/py_lib to PYTHONPATH environment variable.
path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..',
                                    '..', '..', 'util', 'py_lib'))
sys.path.insert(0, path)

import seqan.app_tests as app_tests

def main(source_base, binary_base):
    """Main entry point of the script."""

    print 'Executing test for post_pro'
    print '========================='
    print
    
    ph = app_tests.TestPathHelper(
        source_base, binary_base,
        'sandbox/krakau/apps/post_pro/tests')  # tests dir

    # ============================================================
    # Auto-detect the binary path.
    # ============================================================

    path_to_program = app_tests.autolocateBinary(
      binary_base, 'sandbox/krakau/apps/post_pro', 'post_pro')

    # ============================================================
    # Built TestConf list.
    # ============================================================

    # Build list with TestConf objects, analoguely to how the output
    # was generated in generate_outputs.sh.
    conf_list = []

    # ============================================================
    # First Section.
    # ============================================================

    # App TestConf objects to conf_list, just like this for each
    conf = app_tests.TestConf(
        program=path_to_program,
        redir_stdout=ph.outFile('other.stdout'),
         args=[ph.inFile('reads_mason2_msc5_realign_N6000.CT_GA.sam'),
               ph.inFile('hg18_chr21_3000.fa'),
               ph.inFile('reads_mason2_msc5_realign_N6000.fastq'),
              '-o', ph.outFile('reads_mason2_msc5_realign_N6000_simple.CT_GA.verified.sam'),
              '-gas', str(-4.0), '-ges', str(-1.0), '-der', str(0.001), '-bsc', str(1.0), '-gmr', str(0.2), '-mq', str(0), '-e3', str(4), '-e4', str(5)],
       to_diff=[(ph.inFile('reads_mason2_msc5_realign_N6000_simple.CT_GA.verified.sam'),
                  ph.outFile('reads_mason2_msc5_realign_N6000_simple.CT_GA.verified.sam'))])
    conf_list.append(conf)


    # Another Example.
    conf = app_tests.TestConf(
        program=path_to_program,
        redir_stdout=ph.outFile('other.stdout'),
         args=[ph.inFile('reads_mason2_msc5_realign_N6000.CT_GA.sam'),
               ph.inFile('hg18_chr21_3000.fa'),
               ph.inFile('reads_mason2_msc5_realign_N6000.fastq'),
              '-o', ph.outFile('reads_mason2_msc5_realign_N6000_nonSimple.CT_GA.verified.sam'),
              '-nse', '-nsi', '-nsd', '-gas', str(-4.0), '-ges', str(-1.0), '-der', str(0.001), '-bsc', str(1.0), '-gmr', str(0.2), '-mq', str(0), '-e3', str(4), '-e4', str(5)],
       to_diff=[(ph.inFile('reads_mason2_msc5_realign_N6000_nonSimple.CT_GA.verified.sam'),
                  ph.outFile('reads_mason2_msc5_realign_N6000_nonSimple.CT_GA.verified.sam'))])
    conf_list.append(conf)

    # ============================================================
    # Execute the tests.
    # ============================================================
    failures = 0
    for conf in conf_list:
        res = app_tests.runTest(conf)
        # Output to the user.
        print ' '.join(['post_pro'] + conf.args),
        if res:
             print 'OK'
        else:
            failures += 1
            print 'FAILED'

    # Cleanup.
    ph.deleteTempDir()

    print '=============================='
    print '     total tests: %d' % len(conf_list)
    print '    failed tests: %d' % failures
    print 'successful tests: %d' % (len(conf_list) - failures)
    print '=============================='
    # Compute and return return code.
    return failures != 0


if __name__ == '__main__':
    sys.exit(app_tests.main(main))
